############################################
# Builder stage
############################################
FROM maven:3.9.9-eclipse-temurin-17 AS builder

WORKDIR /workspace
COPY pom.xml ./
COPY src ./src

# Compila o projeto
RUN mvn -B clean package -DskipTests --no-transfer-progress

############################################
# Runtime stage
############################################
FROM eclipse-temurin:17-jre-jammy

WORKDIR /app
COPY --from=builder /workspace/target/*.jar ./app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
